  - name: creating uplinks and downlinks
    template:
      src: templates/leaf-intf.j2
      dest: temp-config/{{inventory_hostname}}/{{inventory_hostname}}.intf.part
    when: type == "qfx"  
  - name: creating uplinks and downlinks for ex
    template:
      src: templates/leaf-ex-intf.j2
      dest: temp-config/{{inventory_hostname}}/{{inventory_hostname}}.intf.part
    when: type == "ex"
