
#This is vlans for your spine only. both spines. vlan for leaf is in their respective host vards. 

vlans:
  V100:
    id: 506
    name: Prod-vlan
  V101:
    id: 705
    name: Produntrust-to-vqfx
    ip: "{{ '10.10.1.1' if inventory_hostname == 'spine-01' else '10.10.1.2' }}"
    mask: 24
    vip:  10.10.1.3
    vrrp_id: 100
    R_IP: "{{ '10.10.1.2' if inventory_hostname == 'spine-01' else '10.10.1.1' }}"  # This is requiref for active active irb


