


---
- hosts: all
  connection: local
  gather_facts: no
  
  tasks:
    - name: create directories for storing of configs
      file:
        path: config/{{inventory_hostname}}
        state: directory

    - name: create temprorary directory
      file:
        path: temp-config/{{inventory_hostname}}
        state: directory

    - name: creating iccp related config
      hosts: mlag
      template:  
        src: templates/mlag.j2
        dest: temp-config/{{inventory_hostname}}/{{inventory_hostname}}.mlag.part

    - name: creating ae related config
      hosts: mlag
      template: 
        src: templates/bundle.j2
        dest: temp-config/{{inventory_hostname}}/{{inventory_hostname}}.bundle.part

    - name: creating uplinks and downlinks
      template:
        src: templates/leaf-intf.j2
        dest: temp-config/{{inventory_hostname}}/{{inventory_hostname}}.intf.part
      when:  type  == 'Jswitch'
 
    - name: creating vlans related config
      template: 
        src: templates/vlan.j2
        dest: temp-config/{{inventory_hostname}}/{{inventory_hostname}}.vlans.part
      when: type == 'Jswitch'
  
    - name: SRX reth config
      hosts: srx
      template:
        src: templates/srx.j2
        dest: config/{{inventory_hostname}}/{{inventory_hostname}}.part.conf

    - name: ospf Protocol config
      template:
        src: templates/proto.j2
        dest: config/{{inventory_hostname}}/{{inventory_hostname}}.port.conf

    - name: assembling the fragments-changes
      assemble:
        src: temp-config/{{inventory_hostname}}
        dest:  config/{{inventory_hostname}}/{{inventory_hostname}}.conf

      

...
