---

- name: Create Directories
  hosts: all:!stand_srx
  connection: local
  gather_facts: no
  roles:
    - setup
  tags:
    - always

- name: Create ICCP
  hosts: mlag
  connection: local
  gather_facts: no
  roles:
    - iccp-config
  tags: 
    - MLAG-Proto

- name: Create Bundle
  hosts: mlag
  connection: local
  gather_facts: no
  roles:
    - mlag
  tags: 
    - MLAG-Bundle

- name: Create Leaf Bundle
  hosts: leaf
  connection: local
  gather_facts: no
  roles:
    - leaf
  tags: 
    - leaf

- name: Create SRX Config
  hosts: clusters
  connection: local
  gather_facts: no
  roles:
    - srx-config
  tags: 
    - cluster

- name: Create Proto Config
  hosts: all:!stand_srx
  connection: local
  gather_facts: no
  roles:
    - protocols
  tags: 
    - proto

- name: Create VLAN config
  hosts: all:!stand_srx:!clusters
  connection: local
  gather_facts: no
  roles:
    - vlans
  tags: 
    - vlans

- name: Assembeling configs
  hosts: all:!stand_srx
  connection: local
  gather_facts: no
  roles:
    - assemble
  tags: 
    - assemble



