mclag_id: "{{ id - ((id//2)*2) }}"

mclag:
  nbr_ae: 10
  mac:  02:05:86:71:d2:00
  rmac: 02:05:86:71:71:10
  enhanced_convergence: "Yes"
  l3_routing: "Yes"
  mode: active-active
  iccp_interface: ae1
  icl_interface: ae0
  chassis_id: "{{ mclag_id }}"
  status_control: "{{ 'active' if mclag_id == '0' else 'standby' }}"
  iccp:
    links:
      - "xe-0/0/2"
    local_ip: "{{ '1.1.1.2' if mclag_id == '0' else '1.1.1.1' }}"
    peer_ip: "{{ '1.1.1.1' if mclag_id == '0' else '1.1.1.2' }}"
  icl:
    links:
      - "xe-0/0/0"
      - "xe-0/0/1"
    description: ICL interface
  mcae:
    to_VCF:
      key: 2
      links:
        - "xe-0/0/3"
    to_SRX-Prod-01:
      key: 3
      links:
        - "xe-0/0/4"
    to_SRX-Prod-02:
      key: 4
      links:
        - "xe-0/0/5"




