ospf:
  Prod:
    area1: 
      type: backbone
      nmbr: 0
      intf:
        - reth0.701
#    area2:
#      type: nbackbone
#      nmbr: 1
#      intf:
#        - reth1.10
  TnD:
    area1:
      type: backbone
      nmbr: 0
      intf:
        - reth0.702
  wane:
    area1:
      type: backbone
      nmbr: 0
      intf:
        - reth1.703
