vlans:
  V100:
    id: 703
    name: Agg-to-vQFX
  V101:
    id: 701
    name: Produntrust-to-vqfx
    ip: "{{ '10.100.3.10' if inventory_hostname == 'spine-01' else '10.100.3.11' }}"
    mask: 29
    vip:  10.100.3.12
    vrrp_id: 100
    R_IP: "{{ '10.100.3.11' if inventory_hostname == 'spine-01' else '10.100.3.12' }}"


